spring.application.name=pos_sys
spring.datasource.url=jdbc:mysql://localhost:3306/db_restaurant2-5
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
